# August 21, 2015
# https://github.com/bevry/base
language: node_js
# ensure npm is the latest version (ignore node versions that can't run it)
# ensure correct dependencies are installed (handled via npm run-script install)
install: "npm install -g npm && npm run-script setup"
# ensure our application is compiled before we run our tests
before_script: "npm run-script compile"
script: "npm test"
node_js:
  - "0.12"
  - iojs
cache:
  directories:
    - node_modules
notifications:
  # Nofity email travisci@bevry.me
  email:
    recipients:
      - travisci@bevry.me

  # Notify slack #updates channel on https://bevry.slack.com
  # Bevry's token available from https://bevry.slack.com/services/4200459714
  # travis encrypt "bevry:$BEVRY_TRAVIS_TOKEN#updates" --add notifications.slack
